spring:
  application:
    name: wings-music
  profiles:
    active: dev
  datasource:
    druid:
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      url: jdbc:${DATABASE_TYPE}://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  flyway:
    enabled: true
    encoding: UTF-8
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: ${SERVER_PORT}


